[package]
name = "ch582-embassy-blinky"
version = "0.1.0"
publish = false
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
embassy-ch58x = { workspace = true, features = ["ch582", "time-driver"] }
embassy-executor = "0.9"
embassy-time = { version = "0.5", features = ["tick-hz-1_000_000"] }
embedded-hal = "1.0"
qingke-rt = { git = "https://github.com/rusted-ch5/qingke-rs.git", rev = "b107f8b4cce3495ff807738cdbb34f25819ca680", default-features = false, features = ["v4", "highcode"] }
