[package]
name = "ch582-embassy-blinky"
version = "0.1.0"
publish = false
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
embassy-ch58x-rs = { workspace = true, features = ["ch582", "time-driver"] }
embassy-executor = "0.9"
embassy-time = { version = "0.5", features = ["tick-hz-1_000_000"] }
embedded-hal = "1.0"
qingke-rs = { version = "=0.6.1-rusted.1", git = "https://github.com/rusted-ch5/qingke-rs.git", rev = "9f2eed7594eb6ea8cd4ae9504e4023698ce05fcd", default-features = false, features = ["v4", "highcode"] }
