[workspace]
members = [
    "examples/ch582-blinky",
    "examples/ch582-embassy-blinky",
    "examples/ch582-uart-echo",
    "examples/ch582-usb-hid",
    "examples/rmk-ch58x",
]
resolver = "2"

[workspace.package]
edition = "2024"
rust-version = "1.92"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
embassy-ch58x = { git = "https://github.com/rusted-ch5/embassy-ch58x.git", rev = "33c320eb35760fea797870b48a13b4c75141a40f", default-features = false }

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = "s"
