[workspace]
members = [
    "examples/ch582-blinky",
    "examples/ch582-embassy-blinky",
    "examples/ch582-uart-echo",
    "examples/ch582-usb-hid",
    "examples/rmk-ch58x",
]
resolver = "2"

[workspace.package]
edition = "2024"
rust-version = "1.92"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
embassy-ch58x-rs = { version = "=0.1.0-alpha.1", git = "https://github.com/rusted-ch5/embassy-ch58x.git", rev = "e4b64fde2f3d2e1c0d566d56b3558d8cb605dbab", default-features = false }

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = "s"
