[workspace]
members = [
    "examples/ch582-blinky",
    "examples/ch582-embassy-blinky",
    "examples/ch582-uart-echo",
    "examples/ch582-usb-hid",
]
resolver = "2"

[workspace.package]
edition = "2024"
rust-version = "1.87"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
embassy-ch58x = { git = "https://github.com/rusted-ch5/embassy-ch58x.git", rev = "3548f3f6af9e475bf52af56ee2c262d21464bea5", default-features = false }

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = "s"
