[package]
name = "rmk-ch58x"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
embassy-ch58x = { workspace = true, features = ["ch582", "gpio", "usb"] }
embassy-executor = "0.9"
qingke-rt = { git = "https://github.com/rusted-ch5/qingke-rs.git", rev = "b107f8b4cce3495ff807738cdbb34f25819ca680", default-features = false, features = ["v4", "highcode"] }
rmk = { git = "https://github.com/rmk-rs/rmk.git", rev = "34d1a5eedf8afd17128cf25ed839adab6475d404", version = "=0.9.0", default-features = false, features = ["async_matrix"] }
