MEMORY
{
  /* CH582M EVT: keep the established 448-KiB Code Flash and 32-KiB SRAM limits. */
  FLASH (rx)  : ORIGIN = 0x00000000, LENGTH = 448K
  RAM   (rwx) : ORIGIN = 0x20000000, LENGTH = 32K
}

REGION_ALIAS("REGION_TEXT", FLASH);
REGION_ALIAS("REGION_RODATA", FLASH);
REGION_ALIAS("REGION_DATA", RAM);
REGION_ALIAS("REGION_BSS", RAM);
REGION_ALIAS("REGION_HEAP", RAM);
REGION_ALIAS("REGION_STACK", RAM);
