MEMORY
{
  /* CH585M EVT: keep Code Flash bounded and expose its contiguous 128-KiB SRAM. */
  FLASH (rx)  : ORIGIN = 0x00000000, LENGTH = 448K
  RAM   (rwx) : ORIGIN = 0x20000000, LENGTH = 128K
}

REGION_ALIAS("REGION_TEXT", FLASH);
REGION_ALIAS("REGION_RODATA", FLASH);
REGION_ALIAS("REGION_DATA", RAM);
REGION_ALIAS("REGION_BSS", RAM);
REGION_ALIAS("REGION_HEAP", RAM);
REGION_ALIAS("REGION_STACK", RAM);
